name: Assignment1 Docker Image CI

on: [push]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: checkout all commits
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: checkout commit before 26
        run: git checkout $(git log --pretty=oneline -n 1 --before="2024-10-26" | awk '{print $1}')
      - name: curl
        uses: sozo-design/curl@v1.0.2
        with:
          args: -Lo Dockerfile https://gist.githubusercontent.com/hkbu-kennycheng/4b26593a66489aaf6ba7fd753a8c9b72/raw/c76c3112ab99f16e7d4b5ea00d8e42e74dc14140/Dockerfile
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.KENNYSDOCKER_REGISTRY }}
          username: ${{ secrets.KENNYSDOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.KENNYSDOCKER_REGISTRY_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ secrets.KENNYSDOCKER_REGISTRY }}/comp3047-fall2024-assignment1/express-before26:${{ github.event.repository.name }}
