name: Docker Image CI

on: [push]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.KENNYSDOCKER_REGISTRY }}
          username: ${{ secrets.KENNYSDOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.KENNYSDOCKER_REGISTRY_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ secrets.KENNYSDOCKER_REGISTRY }}/comp3047-fall2024-assignment1/express:${{ github.event.repository.name }}
